theme: jekyll-theme-hacker
baseurl: ""
url: "https://karthick3018.github.io/blogs-helper/"
github:
  zip_url: https://github.com/karthick3018/blogs-helper/blob/main/blogs-helper.zip
  remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme